### ISSUE TITLE
Tag "latest" is not updated to the latest released version in Docker Hub

### ISSUE THREAD

**Issue by jobenvil** [eko/pihole-exporter#119]
Which prevents automatically auto updates to the lastest version.

Until now, I have to manually update the tag and then deploy, which is obiouosly not great. 

![image](https://user-images.githubusercontent.com/11994245/153659817-01e637e7-55d4-4f1e-b6d0-dc565745e78e.png)

**Comment by Kybeer** [comment]
Hello,
Latest Container images is not updated with 0.3.0. Would it be possible to do?

**Comment by rodneyshupe** [comment]
+1 for this as it also is only an amd64 version.

**Comment by andonovski** [comment]
+1

**Comment by goodshort** [comment]
Thank you very much for opening this issue. I have been trying for an hour to understand what I am doing wrong when providing 2 IP addresses to PIHOLE_HOSTNAME.
I will now use v0.3.0 and keep an eye on new updates instead of using latest until this is resolved

**Comment by Zozman** [comment]
Would maybe adding a step [after this step in the GitHub Actions workflow](https://github.com/eko/pihole-exporter/blob/master/.github/workflows/tag.yml#L47) to tag it with `latest` on a push to master work?  Something like:

```yaml
- name: Tag and push latest
  if: ${{ github.ref == 'refs/heads/master' }}
  run: |
    docker image tag ekofr/pihole-exporter:${{ steps.get_version.outputs.TAG_NAME }} ekofr/pihole-exporter:latest
    docker image push ekofr/pihole-exporter:latest
```

Not sure if this is the most efficient way to do it but I could file a PR if needed.
