### ISSUE TITLE
High CPU consumption

### ISSUE THREAD

**Issue by kuleshov-aleksei** [eko/pihole-exporter#120]
Hello!
I have pihole-explorer in docker. The container loads the system (raspberry pi) more than 100% after 2-3 days of running. It completely freezes raspberry pi. Even ssh connection can't be established. This is not first time when it happens
![image](https://user-images.githubusercontent.com/10367317/154648731-51950858-64c3-475b-846a-2f23e6059597.png)

Also, prometheus is unable to get metrics at time of overload:
![image](https://user-images.githubusercontent.com/10367317/154653120-57f53a9a-1dce-445a-a028-5a8571534370.png)

I use a bit outdated version: v0.0.10. I've updated to latest version (v0.2.0) but from changelog I don't think that this bug was fixed

**Steps for Reproduction**

pihole_exporter container is created by docker-compose:
```yml
version: '3'
services:
  pihole_exporter:
    image: ekofr/pihole-exporter:0.0.10
    container_name: monitoring_pihole_exporter
    restart: unless-stopped
    environment:
      - PORT=9617
      - INTERVAL=30s
      - PIHOLE_HOSTNAME=${ENV_PIHOLE_HOSTNAME}
      - PIHOLE_PASSWORD=${ENV_PIHOLE_PASSWORD}
      - PIHOLE_PORT=4000
    expose:
      - 9617
    networks:
      - pi
```

**Expected behavior**:

Software should not load whole system

**Actual behavior**:

System overloads and freezes

**Platforms**:

Raspberry pi 4 (4Gb)
Ubuntu 20.04.2 LTS
docker-compose version 1.25.0
Docker version 20.10.7

Pi hole is running on another raspberry pi 3b+ (also Ubuntu 20.04.2 LTS)

**Versions**:

v0.0.10 in docker
