### ISSUE TITLE
Docker Build Stuck on "Starting HTTP server"

### ISSUE THREAD

**Issue by geoscoutCJ** [eko/pihole-exporter#161]
I am trying to run the pihole-exporter using a docker container, using both an .env file and a docker-compose.yaml file. 

Everything seems to work fine up until the "Starting HTTP server" portion of the start-up, and then the set-up just stops there.

**Steps for Reproduction**

1. My .env file has the following:
```
PIHOLE_HOSTNAME=192.168.1.5X,192.168.1.5Y
PIHOLE_PASSWORD=mypassword
PORT=9617
```
2. My docker-compose.yaml file contains the following: 
```
version: '3'
services:
  pihole-exporter:
    image: ekofr/pihole-exporter:latest
    restart: always
    env_file:
    - 'piexporter.env'
```
3. I then run `sudo docker-compose run pihole-exporter`
4. Which gives me this:
![stuckonhttpserver](https://user-images.githubusercontent.com/97177582/212928828-ff078b71-df3d-4421-b7ad-01470d8b75cc.png)

For hardware, I am running on a Raspberry Pi 3 Model B Rev 1.2. OS, I am running DietPi v8.13.2.

Any ideas where this may be going wrong or additional troubleshooting steps?

Thanks,
Caleb
