### ISSUE TITLE
An error occured while contacting pihole

### ISSUE THREAD

**Issue by daviddanko** [eko/pihole-exporter#258]
I am using this exporter for quite a while now and I was happy to see that the exporter now supports pihole v6.0. Thanks for everyone involved.

However, it doesn't seem to be working for me. Was there any change in how should the compose or env file look like? This was working before v6 for me:

compose:
```
  pihole-exporter:
    container_name: pihole-exporter
    image: ekofr/pihole-exporter:latest
    restart: unless-stopped
    environment:
      - PIHOLE_HOSTNAME=${PIHOLE_1_HOSTNAME},${PIHOLE_2_HOSTNAME}
      - PIHOLE_API_TOKEN=${PIHOLE_1_TOKEN},${PIHOLE_2_TOKEN}
      - PORT=${PIHOLE_EXPORTER_PORT}
    ports:
      - ${PIHOLE_EXPORTER_PORT}:${PIHOLE_EXPORTER_PORT}
    networks:
      - tools
```

env:
```
PIHOLE_1_HOSTNAME=piholelxc.ddanko.eu
PIHOLE_1_TOKEN="TY/tgnre6L1icQiKwVFXm3FjirLJgo8wm61h/coNLVE="
PIHOLE_2_HOSTNAME=rpi-01.ddanko.eu
PIHOLE_2_TOKEN="ja0U9e7k53Cf/SNU4Fizc/OhT1F4F2sYkUdDPOxTwjY="
PIHOLE_EXPORTER_PORT=9617
```

I can login with those URLs using the tokens, but the exporter doesn't quite like them.

logs:
```
time="2025-02-22T17:48:46Z" level=info msg="Collecting from rpi-01.ddanko.eu"
time="2025-02-22T17:48:46Z" level=info msg="Session expired, re-authenticating"
time="2025-02-22T17:48:46Z" level=info msg="Authenticatinghttp://rpi-01.ddanko.eu:80/api/auth"
time="2025-02-22T17:48:46Z" level=info msg="Collecting from piholelxc.ddanko.eu"
time="2025-02-22T17:48:46Z" level=info msg="Session expired, re-authenticating"
time="2025-02-22T17:48:46Z" level=info msg="Authenticatinghttp://piholelxc.ddanko.eu:80/api/auth"
time="2025-02-22T17:48:46Z" level=info msg="An error occured while contacting piholelxc.ddanko.eu: error fetching stats summary: authentication failed, status code: 401"
time="2025-02-22T17:48:46Z" level=info msg="An error occured while contacting rpi-01.ddanko.eu: error fetching stats summary: authentication failed, status code: 401"
```
