### ISSUE TITLE
Stuck at "Starting HTTP server"

### ISSUE THREAD

**Issue by target2804** [eko/pihole-exporter#267]
When running the pihole_exporter in docker, it gets stuck at "starting http server".

**Steps for Reproduction**

1. Setup of the pihole_exporter by doing:
```
docker run \
  -e 'PIHOLE_HOSTNAME=192.168.178.10' \
  -e 'PIHOLE_PASSWORD=12345' \
  -e 'INTERVAL=30s' \
  -e 'PORT=9617' \
  -p 9617:9617 \
  ekofr/pihole-exporter:latest
```

2. Prometheus-conf is set up correctly:
```
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  # external_labels:
  #  monitor: 'codelab-monitor'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node:exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'pihole'
    static_configs:
      - targets: ['localhost:9617']
```

**Expected behavior**: Pihole exporter sending metrics to prometheus.

**Actual behavior**: exporter gets stuck at starting the http-server and doesnt do anything else.

> time="2025-03-20T11:27:46Z" level=info msg=------------------------------------
> 
> time="2025-03-20T11:27:46Z" level=info msg="-  Pi-hole exporter configuration  -"
> 
> time="2025-03-20T11:27:46Z" level=info msg=------------------------------------
> 
> time="2025-03-20T11:27:46Z" level=info msg="Go version: go1.24.1"
> 
> time="2025-03-20T11:27:46Z" level=info msg="PIHoleProtocol : [http]"
> 
> time="2025-03-20T11:27:46Z" level=info msg="PIHoleHostname : [192.168.178.10/admin]"
> 
> time="2025-03-20T11:27:46Z" level=info msg="PIHolePort : [80]"
> 
> time="2025-03-20T11:27:46Z" level=info msg="Pi-hole Authentication Method : PIHolePassword"
> 
> time="2025-03-20T11:27:46Z" level=info msg="BindAddr : 0.0.0.0"
> 
> time="2025-03-20T11:27:46Z" level=info msg="Port : 9617"
> 
> time="2025-03-20T11:27:46Z" level=info msg="Timeout : 5s"
> 
> time="2025-03-20T11:27:46Z" level=info msg=------------------------------------
> 
> time="2025-03-20T11:27:46Z" level=info msg="New Prometheus metric registered: domains_blocked"
> 
> time="2025-03-20T11:27:46Z" level=info msg="New Prometheus metric registered: dns_queries_today"
> 
> time="2025-03-20T11:27:46Z" level=info msg="New Prometheus metric registered: ads_blocked_today"
> 
> time="2025-03-20T11:27:46Z" level=info msg="New Prometheus metric registered: ads_percentag_today"
> 
> time="2025-03-20T11:27:46Z" level=info msg="New Prometheus metric registered: unique_domains"
> 
> time="2025-03-20T11:27:46Z" level=info msg="New Prometheus metric registered: queries_forwarded"
> 
> time="2025-03-20T11:27:46Z" level=info msg="New Prometheus metric registered: queries_cached"
> 
> time="2025-03-20T11:27:46Z" level=info msg="New Prometheus metric registered: clients_ever_seen"
> 
> time="2025-03-20T11:27:46Z" level=info msg="New Prometheus metric registered: unique_clients"
> 
> time="2025-03-20T11:27:46Z" level=info msg="New Prometheus metric registered: dns_queries_all_types"
> 
> time="2025-03-20T11:27:46Z" level=info msg="New Prometheus metric registered: reply"
> 
> time="2025-03-20T11:27:46Z" level=info msg="New Prometheus metric registered: top_queries"
> 
> time="2025-03-20T11:27:46Z" level=info msg="New Prometheus metric registered: top_ads"
> 
> time="2025-03-20T11:27:46Z" level=info msg="New Prometheus metric registered: top_sources"
> 
> time="2025-03-20T11:27:46Z" level=info msg="New Prometheus metric registered: forward_destinations"
> 
> time="2025-03-20T11:27:46Z" level=info msg="New Prometheus metric registered: destination_responsetime"
> 
> time="2025-03-20T11:27:46Z" level=info msg="New Prometheus metric registered: destination_responsevariance"
> 
> time="2025-03-20T11:27:46Z" level=info msg="New Prometheus metric registered: request_rate"
> 
> time="2025-03-20T11:27:46Z" level=info msg="New Prometheus metric registered: querytypes"
> 
> time="2025-03-20T11:27:46Z" level=info msg="New Prometheus metric registered: status"
> 
> time="2025-03-20T11:27:46Z" level=info msg="Creating client with config <Config@400004A320 PIHoleProtocol=http, PIHoleHostname=192.168.178.10/admin, PIHolePort=80, PIHolePassword=*****, BindAddr=, Port=0>\n"
> 
> time="2025-03-20T11:27:46Z" level=info msg="Starting HTTP server"

**Platforms**: Pihole v4 ARM

piOS debian12 Bookworm

**Versions**:

Which versions are you running?
pihole_exporter:latest
