### ISSUE TITLE
No data in Grafana / Follow up your advise

### ISSUE THREAD

**Issue by JeromeX** [eko/pihole-exporter#32]
I just installed on my Pi4 pihole as usal, installed prometheus as well go and going through your readme. Everything is running, but there is no way to see data in grafana. Can you help me? What do i need configure on grafana site? What's wrong, what must i check?

![Bildschirmfoto 2020-03-16 um 18 02 01](https://user-images.githubusercontent.com/15369779/76782261-51a69c80-67b0-11ea-94ff-9e5a0efb2db5.png)
![Bildschirmfoto 2020-03-16 um 18 04 11](https://user-images.githubusercontent.com/15369779/76782547-b9f57e00-67b0-11ea-8b27-f8b7bb8205bb.png)

**Comment by clintcolding** [comment]
Have you added a scrape job to the prometheus.yml? Something like:

```
- job_name: pihole
  honor_timestamps: true
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - pihole-exporter.mydomain.com
```

If so, on the targets page of Prometheus, is the endpoint marked as up?

**Comment by JeromeX** [comment]
> Have you added a scrape job to the prometheus.yml? Something like:
> 
> ```
> - job_name: pihole
>   honor_timestamps: true
>   metrics_path: /metrics
>   scheme: http
>   static_configs:
>   - targets:
>     - pihole-exporter.mydomain.com
> ```

> i filled up, like on instruction page, but no success. If you have experience in this can i invite you for a remote help or something else? it might be very useful to know it must be configured step by step.  Any help is preciated.

**Comment by shaned24** [comment]
Do you have your prometheus server running on the same machine as the pi-hole-exporter?

if so then you can see your domain to `localhost` and don't forget the port `9617`
```
- job_name: pihole
  honor_timestamps: true
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets: ["localhost:9617"]
```
