### ISSUE TITLE
connect: connection refused

### ISSUE THREAD

**Issue by AlfaJackal** [eko/pihole-exporter#47]
I set up my prometheus and pihole-exporter with docker on my synology. Unfortunately no data will be sent to prometheus. And it seems, `/metrics` on port 9617 is also not available though data from my pihole has been received.

- `targets` tells me, my `localhost:9617/metrics` is down, no data has been written. `Get "http://localhost:9617/metrics": dial tcp 127.0.0.1:9617: connect: connection refused`
- `http://10.0.0.13/admin/api.php?summaryRaw&overTimeData&topItems&recentItems&getQueryTypes&getForwardDestinations&getQuerySources&jsonForceObject`shows data also the logs from pihole-exporter so the exporter itself works, but without writing the data.

prometheus.yml:
```
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'pihole'
    static_configs:
    - targets: ['localhost:9617']
```

Default prometheus data has been written from that scrape but not from pihole scrape which is running on the same machine. 

Here are my settings:
```
Environment:
PIHOLE_HOSTNAME=10.0.0.13
PIHOLE_API_TOKEN=xxx 
INTERVAL=30s
PORT=9617

Ports:
9617:9617 
```
