### ISSUE TITLE
Docker deployment - memory leak

### ISSUE THREAD

**Issue by joachimnielandt** [eko/pihole-exporter#54]
I noticed a memory consumption of 1.3GB for piholeexporter last I checked my monitoring. After restarting, that dropped to 20MB, which promply started climbing steadily again. In 3 hours it went from 29MB to 37MB. I guess there's a memory leak?

I'm using the following docker-compose setup (pulled and checked that the latest also had the behaviour):
```
  piholeexporter:
    container_name: piholeexporter
    image: ekofr/pihole-exporter:latest
    depends_on:
      - pihole
    restart: unless-stopped
    environment:
      PIHOLE_HOSTNAME: 'x'
      PIHOLE_PASSWORD: 'x'
      INTERVAL: '30s'
      PORT: '9617'
```
