### ISSUE TITLE
random values in dashboard

### ISSUE THREAD

**Issue by DVDAndroid** [eko/pihole-exporter#58]
It's the first time I'm working with Grafana, so probably it's my fault

**Steps for Reproduction**

1. launch `docker-compose -f pihole.yml up -d`
2. launch `docker-compose -f grafana.yml up -d`
3. import this dashboard
4. `localhost:3000/thisdashboard`

**Expected behavior**:
Working dashboard

**Actual behavior**:
random values in dashboard

![image](https://user-images.githubusercontent.com/6277172/88970504-d05d2b80-d2b2-11ea-9c9a-045f8996f3ee.png)

**Platforms**:

Windows 10 Pro 1909, Chrome 84, PiHole 5.1, Docker

```Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:43:18 2020
 OS/Arch:           windows/amd64
 Experimental:      false
Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:49:27 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

docker compose pihole.yml
```yaml
version: '3.3'
services:
  pihole:
    container_name: pihole
    image: pihole/pihole
    cap_add:
      - NET_ADMIN
    dns:
      - 127.0.0.1
      - 1.1.1.1
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '67:67/udp'
      - '8053:80/tcp'
    volumes:
      - './pihole/pihole:/etc/pihole/'
      - './pihole/dnsmasq.d/:/etc/dnsmasq.d/'
    environment:
      - TZ='Europe/Rome'
      - ServerIP=192.168.1.102
      - WEBPASSWORD=password
      - PROXY_LOCATION=pihole
      - VIRTUAL_HOST=pihole.localhost
      - VIRTUAL_PORT=80
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.rule=Host(`pihole.localhost`)"
      - "traefik.http.routers.pihole.entrypoints=http"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
```

docker compose grafana & pihole-exporter:
```yml
version: '3.3'
services:
  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - '3000:3000'
    volumes:
      - './grafana:/var/lib/grafana'
    environment:
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
      
  pihole-exporter:
    container_name: pihole-exporter
    image: ekofr/pihole-exporter
    ports:
      - '9617:9617'
    environment:
      - PIHOLE_HOSTNAME=192.168.1.102
      - PIHOLE_PORT=8053
      - PIHOLE_PASSWORD=password
      - INTERVAL=30s
      - PORT=9617
```

pihole api is working: `http://192.168.1.102:8053/admin/api.php?summaryRaw&overTimeData&topItems&recentItems&getQueryTypes&getForwardDestinations&getQuerySources&jsonForceObject`
response:
```json
{
  "domains_being_blocked": 452466,
  "dns_queries_today": 59,
  "ads_blocked_today": 39,
  "ads_percentage_today": 66.101692,
  "unique_domains": 25,
  "queries_forwarded": 19,
  "queries_cached": 1,
  "clients_ever_seen": 2,
  "unique_clients": 2,
  "dns_queries_all_types": 59,
  "reply_NODATA": 0,
  "reply_NXDOMAIN": 0,
  "reply_CNAME": 8,
  "reply_IP": 44,
  "privacy_level": 0,
  "status": "enabled",
  "gravity_last_updated": {
    "file_exists": true,
    "absolute": 1596133973,
    "relative": {
      "days": 0,
      "hours": 1,
      "minutes": 54
    }
  }
}
```

notes: pihole admin port is 8053, because I need to have traefik on port 80; I can login to pihole admin via `pihole.localhost` or `192.168.1.102:8083/admin`; I'm working in localhost, no other devices, no rasperrypi; tested with a clean version of pihole but I have the same problem
