### ISSUE TITLE
No Data Scraped by Prometheus

### ISSUE THREAD

**Issue by TrikkStar** [eko/pihole-exporter#62]
After spending several hours trying to get this script working I'm at a loss as to what's going wrong.

Running Docker on RPi3 w/ latest Rasbian Lite. (Though I want to run both this container and Prometheus on a separate server, running it on the pi to eliminate variables)
Deployment:
```
$ API_TOKEN=$(awk -F= -v key="WEBPASSWORD" '$1==key {print $2}' /etc/pihole/setupVars.conf)
$ docker run --name pihole-exporter -d -p9617:9617 -e 'PIHOLE_HOSTNAME=192.168.1.13' -e "PIHOLE_API_TOKEN=$API_TOKEN" -e 'PORT=9617' -e 'INTERVAL=10s' ekofr/pihole-exporter:0.0.9
$ docker run --name prometheus -d -p 9090:9090 --mount source=prometheus,target=/etc/prometheus/ prom/prometheus
```

prometheus.yml:
```
# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'pihole'
    honor_timestamps: true
    metrics_path: /metrics
    scheme: http
    static_configs:
    - targets: ['localhost:9617']
```
