### ISSUE TITLE
No data returned for few of the metrics

### ISSUE THREAD

**Issue by limpep** [eko/pihole-exporter#75]
Hi @eko 

I am not getting any data for the following metrics nor is it returns in Prometheus, 

pihole_top_queries
pihole_top_ads
pihole_top_queries
pihole_top_ads
pihole_forward_destinations

Other seems to work fine.

I am using docker-compose to run the container. The image I have built using the latest code from the repo.

```
 version: "3"
 services:

    pi-hole-exporter:
      image: pihole-export
      environment:
       - PUID=1000
       - PGID=1000
       - PIHOLE_HOSTNAME=192.168.1.77
       - PIHOLE_API_TOKEN="MY_AWESOME_TOKEN"
       - INTERVAL=30s
       - PORT=9617
      logging:
        driver: "json-file"
        options:
         max-size: 10m
         max-file: "3"
         labels: "pihole-exporter"
      ports:
        - "9617:9617"
      restart: unless-stopped
```
I am using a raspberry 4 to run the exporter.
```
  `.::///+:/-.        --///+//-:``    pi@raspberrypi
 `+oooooooooooo:   `+oooooooooooo:    --------------
  /oooo++//ooooo:  ooooo+//+ooooo.    OS: Raspbian GNU/Linux 10 (buster) armv7l
  `+ooooooo:-:oo-  +o+::/ooooooo:     Host: Raspberry Pi 4 Model B Rev 1.4
   `:oooooooo+``    `.oooooooo+-      Kernel: 5.10.11-v7l+
     `:++ooo/.        :+ooo+/.`       Uptime: 19 hours, 50 mins
        ...`  `.----.` ``..           Packages: 1888 (dpkg)
     .::::-``:::::::::.`-:::-`        Shell: bash 5.0.3
    -:::-`   .:::::::-`  `-:::-       Terminal: /dev/pts/1
   `::.  `.--.`  `` `.---.``.::`      CPU: BCM2711 (4) @ 1.500GHz
       .::::::::`  -::::::::` `       Memory: 1368MiB / 7874MiB
 .::` .:::::::::- `::::::::::``::.
-:::` ::::::::::.  ::::::::::.`:::-
::::  -::::::::.   `-::::::::  ::::
-::-   .-:::-.``....``.-::-.   -::-
 .. ``       .::::::::.     `..`..
   -:::-`   -::::::::::`  .:::::`
   :::::::` -::::::::::` :::::::.
   .:::::::  -::::::::. ::::::::
    `-:::::`   ..--.`   ::::::.
      `...`  `...--..`  `...`
            .::::::::::
             `.-::::-`
```
here is my docker version
```
Client: Docker Engine - Community
 Version:           20.10.3
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        48d30b5
 Built:             Fri Jan 29 14:33:57 2021
 OS/Arch:           linux/arm
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.3
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       46229ca
  Built:            Fri Jan 29 14:31:57 2021
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
