### ISSUE TITLE
request: support use of docker secret for pihole password

### ISSUE THREAD

**Issue by jeremyhayes** [eko/pihole-exporter#91]
Feature request to support reading pihole password and/or api key from docker secrets.
* https://docs.docker.com/engine/swarm/secrets/#build-support-for-docker-secrets-into-your-images

The "standard" way would be to support a `PIHOLE_PASSWORD_FILE` env var, and read the file contents into the configuration, falling back to the existing variable. 

For reference, here is the PR which added this support to pihole itself:
* https://github.com/pi-hole/docker-pi-hole/pull/584

**Steps for Reproduction**

1. Setup the following docker-compose
```yml
version: '3.8'

services:

  pihole:
    image: pihole/pihole:v5.8.1
    environment:
      # pihole supports reading password from a mounted secret
      - WEBPASSWORD_FILE=/run/secrets/pihole-password
    secrets:
      - pihole-password
    # other pihole configuration, ports etc

  pihole-exporter:
    image: ekofr/pihole-exporter:v0.0.11
    environment:
      - PIHOLE_HOSTNAME=pihole
      - PIHOLE_PASSWORD_FILE=/run/secrets/pihole-password

secrets:
  pihole-password:
    external: true
```

2. Create the docker secret
```sh
$ echo "hunter2" | docker secret create pihole-password
```

3. Deploy the stack
```sh
$ docker stack deploy -c docker-compose.yml test
```

**Expected behavior**:
pihole-exporter would read the contents of `/run/secrets/pihole-password` as the password

**Actual behavior**:
`PIHOLE_PASSWORD_FILE` is ignored; exporter returns only the "unauthenticated" metrics.

**Platforms**:
Docker swarm cluster.

**Versions**:
`ekofr/pihole-exporter:v0.0.11`

**Comment by moritzj29** [comment]
would love to see this implemented!

**Comment by lebenitza** [comment]
Thanks to you @jeremyhayes and to https://github.com/pi-hole/docker-pi-hole/pull/584 it was easy to find a quick workaround to this:
```Dockerfile
FROM ekofr/pihole-exporter:v0.4.0 as source

FROM alpine:3.17

RUN apk update --no-cache && apk add bash

COPY --from=source /root/pihole-exporter /root/pihole-exporter
COPY start.sh /root/start.sh

CMD /root/start.sh
```
```sh
#!/bin/bash

# See: https://github.com/pi-hole/docker-pi-hole/pull/584
load_password_secret() {
   # If PIHOLE_PASSWORD is not set at all, attempt to read password from PIHOLE_PASSWORD_FILE,
   # allowing secrets to be passed via docker secrets
   if [ -z "${PIHOLE_PASSWORD+x}" ] && [ -n "${PIHOLE_PASSWORD_FILE}" ] && [ -r "${PIHOLE_PASSWORD_FILE}" ]; then
     export PIHOLE_PASSWORD=$(<"${PIHOLE_PASSWORD_FILE}")
   fi;
}

load_password_secret

exec /root/pihole-exporter

```

**Comment by steventblack** [comment]
Building on the previous work above from @lebenitza, here's an example docker compose file that dynamically builds the image from the Docker file above and uses docker secrets to provide the password. It also supports the change in pihole v6 for https by providing a way to pass the CA certs that pihole dynamically generates (or any other CA for that matter).

```
name: pihole-exporter
services:
  pihole-exporter:
    build:
      context: .
      dockerfile: Dockerfile
      
    image: pw-pihole-exporter
    container_name: pihole-exporter
    restart: unless-stopped
    ports:
      - 9617:9617
    volumes:
    # The SSL cert contains *only* the authority for the 
    # pihole self-signed access. If different certs are used on the
    # pihole, then add the CA to the ./ssl/certs directory
    # the pihole certs can be found at /etc/pihole/tls_ca.crt
      - type: bind
        source: ./ssl/certs
        target: /etc/ssl/certs
        read_only: true
    environment:
      PIHOLE_PROTOCOL: https
      PIHOLE_PORT: 443
      PIHOLE_PASSWORD_FILE: /run/secrets/pihole_password
      PIHOLE_HOSTNAME: pihole.example.com
    secrets:
      - pihole_password

# The secret should be the admin password for accessing the pihole
# Place it in the pihole-password.txt file and be sure the file permissions
# are restricted to limit access. (i.e. chmod 600 pihole-password.txt)
# This should also be on the .gitignore list so it can't be checked in.
secrets:
  pihole_password:
    file: ./pihole-password.txt
```
